// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2qAc4d7XACyqy02rvHqFfzGG2x1yrg94',
    appId: '1:669576192029:web:bc92ff373f52d2b5bce6f4',
    messagingSenderId: '669576192029',
    projectId: 'covidtracker-7646b',
    authDomain: 'covidtracker-7646b.firebaseapp.com',
    storageBucket: 'covidtracker-7646b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARS9dXXW7oCN-KhLMXtFCXnNyJDDMmO2E',
    appId: '1:669576192029:android:25d540371bbed8dcbce6f4',
    messagingSenderId: '669576192029',
    projectId: 'covidtracker-7646b',
    storageBucket: 'covidtracker-7646b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rYiTpxb8ewyYhFq0S-IbTV5eiOM32Wk',
    appId: '1:669576192029:ios:3e0329e4b37b5bddbce6f4',
    messagingSenderId: '669576192029',
    projectId: 'covidtracker-7646b',
    storageBucket: 'covidtracker-7646b.appspot.com',
    iosClientId: '669576192029-3p86m7hu75b8fm9vhr72fhtlkvm212to.apps.googleusercontent.com',
    iosBundleId: 'com.example.covidapp',
  );
}
